services:
  zerotier-swag:
    build: .
    container_name: zerotier-swag-gateway
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      # SSL Configuration (default: HTTP-only)
      - SSL_ENABLED=${SSL_ENABLED:-false}
      - URL=${URL:-example.com}
      - EMAIL=${EMAIL:-}

      # ZeroTier Configuration (required)
      - NETWORK_ID=${NETWORK_ID:-}

      # Nginx reverse proxy endpoints
      # Format: service1:port1,service2:port2,service3:port3
      - ENDPOINTS=${ENDPOINTS:-wordpress:80}

      # Optional domains (one per endpoint in same order)
      # - DOMAINS=example.com,api.example.com,grafana.example.com

      # Network Configuration
      - ZMESH_NETWORK_NAME=${ZMESH_NETWORK_NAME:-zmesh}
      - ZMESH_SUBNET=${ZMESH_SUBNET:-10.69.42.0/24}
      - ZMESH_BRIDGE_NAME=${ZMESH_BRIDGE_NAME:-br-zmesh}
      - ZMESH_GATEWAY_IP=${ZMESH_GATEWAY_IP:-10.69.42.1}
      - ZMESH_AUTO_CLEANUP=${ZMESH_AUTO_CLEANUP:-true}

      # Additional SWAG environment variables (only used when SSL_ENABLED=true)
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - VALIDATION=${VALIDATION:-http}
      - SUBDOMAINS=${SUBDOMAINS:-www,}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS:-false}
      - EXTRA_DOMAINS=${EXTRA_DOMAINS:-}
      - STAGING=${STAGING:-false}
    volumes:
      - swag_config:/config
      - /var/run/docker.sock:/var/run/docker.sock  # Required for network creation/cleanup
      # Optional: Mount ZeroTier identity for persistence
      # - ./zerotier-identity:/var/lib/zerotier-one

volumes:
  swag_config: