version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: ${SITE_NAME}-wp
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DEBUG=0
      - WORDPRESS_CONFIG_EXTRA=define('DISALLOW_FILE_EDIT', true);
    volumes:
      - wp_data:/var/www/html
    user: "1000:1000"
    networks:
      - internal
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.6
    container_name: ${SITE_NAME}-db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=y
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal
    restart: unless-stopped

  gateway:
    image: ghcr.io/zachhandley/zerotier-docker-gateway:latest
    container_name: ${SITE_NAME}-gateway
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Site identification (used for DNS-based service discovery)
      - SITE_NAME=${SITE_NAME}

      # ZeroTier Configuration
      # The gateway will get an IP like 10.147.17.5 from ZeroTier
      - NETWORK_IDS=${NETWORK_ID}

      # Gateway Mode - Routes ZeroTier traffic to Docker network
      # inbound = ZeroTier (10.x.x.x) → Docker network (172.x.x.x)
      - GATEWAY_MODE=inbound

      # Caddy Reverse Proxy Endpoints
      # What services to expose (format: service:port,service2:port2)
      - ENDPOINTS=${ENDPOINTS:-wordpress:80}

      # Optional: Custom domains per endpoint
      # - DOMAINS=wp-site1.zmesh,api.zmesh

      # SSL Configuration (default: false, keep HTTP for ZeroTier)
      # Only enable if you have a public domain pointing to this server
      - SSL_ENABLED=${SSL_ENABLED:-false}
      - URL=${DOMAIN:-}
      - EMAIL=${EMAIL:-}

      # Optional: Interface overrides (auto-detected by default)
      # - LO_DEV=eth0  # Local Docker interface
      # - ZT_DEV=ztxxxxxx  # ZeroTier interface name
    volumes:
      - zt_data:/var/lib/zerotier-one
      - caddy_data:/data/caddy
    networks:
      - internal
    healthcheck:
      test: ["CMD", "zerotier-cli", "info"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s
    depends_on:
      - wordpress

volumes:
  wp_data:
  db_data:
  zt_data:
  caddy_data:

networks:
  internal:
    driver: bridge
    # Each project gets its own isolated network
    name: ${SITE_NAME}_internal
