version: '3.8'

services:
  coredns:
    build: .
    # Or use pre-built image:
    # image: ghcr.io/zachhandley/zerotier-docker-gateway-dns:latest
    container_name: zerotier-dns
    restart: unless-stopped

    # Required for host DNS configuration
    privileged: true

    ports:
      # Map container's 53 to host's 5353 (systemd-resolved uses 53)
      - "5353:53/udp"
      - "5353:53/tcp"

    environment:
      # ZeroTier API Configuration
      - ZEROTIER_API_KEY=${ZEROTIER_API_KEY}
      - NETWORK_ID=${NETWORK_ID}

      # Optional: Use ZTNet instead of my.zerotier.com
      - ZTNET_URL=${ZTNET_URL:-https://my.zerotier.com}

    volumes:
      # Zone file storage
      - dns_data:/data

      # Host systemd-resolved configuration (for auto-setup)
      - /etc/systemd:/host/systemd

      # Required for nsenter to restart systemd-resolved
      - /proc:/proc:ro

    healthcheck:
      test: ["CMD", "nslookup", "-port=53", "ns.zmesh", "127.0.0.1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  dns_data:
